### PR TITLE
Added message on error modal for Safari Browser

### PR DESCRIPTION
**Pull request by Kourchenko**

### CODE REVIEW

**Comment by ryanrolds** [comment]
When I get to the location view, select `Use my location`, and click `Get my location` the button changes to `Loading...` even after it gets the location and I'm allowed to proceed. This should say `Done` or `Thank you` and turn to a disabled state unless they change their location type selection.

**Comment by Kourchenko** [comment]
> 
> 
> When I get to the location view, select `Use my location`, and click `Get my location` the button changes to `Loading...` even after it gets the location and I'm allowed to proceed. This should say `Done` or `Thank you` and turn to a disabled state unless they change their location type selection.

Fixed with merging 'master' branch.
https://github.com/Hack4Eugene/SpeedUpAmerica/blob/20f3609fd23feda7c7171bd317e9fcc48e823afe/app/assets/javascripts/home.coffee#L135

**Comment by ryanrolds** [comment]
Cool. Pulling the latest commit fix. 

The button does change back to "Get my location" after a second or two. Any reason it doesn't just keep the `Done` label and become disabled? It sounds like this behavior wasn't implemented in this PR.

**Comment by Kourchenko** [comment]
> 
> 
> Cool. Pulling the latest commit fix.
> 
> The button does change back to "Get my location" after a second or two. Any reason it doesn't just keep the `Success` text and become disabled? It sounds like this behavior wasn't implemented in this PR.

No reason. I have it show 'Success!' and then switch over to 'Get My Location' in case the user clicks on another radio button.
In this PR, I made it so that as soon as the user clicks 'Get My Location', it turns to 'Loading'. There is a lag between when the AJAX request begins and when the button changes to 'Loading'.

Also in this PR, if an error occurs while getting location (after the user clicked 'Get My Location'), then the button simply goes back to 'Get My Location'. After that, they can click on location or will be shown our error modal popup.

**Comment by ryanrolds** [comment]
I like the `Loading...`, I'm just not sure why we would want to allow users to click "Get my location" multiple times if they have selected another location type first.

**Comment by ryanrolds** [comment]
We are showing users two green buttons makes what the users need to do next unclear, especially if they look away and dont' see the success text. Users often have short attention spans and can't remember more than 5 seconds into the past.

**Pull request merged**
