### PR TITLE
Governance and contribution proposal

### PR DESCRIPTION
**Pull request by ryanrolds**
This PR proposes that the project adopts a Liberal Contribution governance model copied from Node.js Foundation. As part of adopting this, I suggest we follow the consensus seeking process outlined in the proposed CONTRIBUTING.md, barring automatic acceptance in the absence of objections - we want positive confirmation from people involved in the project.

Included is a recommend initial set of committers and TC members. Anyone on the lists that don't want to be please speak up. If you want someone added, comment with their name and we can discuss.

The CONTRIBUTION.md and CODE_OF_CONDUCT.md are minimally edited:

``` diff
$ git diff ../CONTRIBUTING.md CONTRIBUTING.md
diff --git a/../CONTRIBUTING.md b/CONTRIBUTING.md
index 7b303e4..81528d7 100644
--- a/../CONTRIBUTING.md
+++ b/CONTRIBUTING.md
@@ -1,8 +1,4 @@
-# Node.js Community Contributing Guide 1.0
-
-This document describes a very simple process suitable for most projects
-in the Node.js ecosystem. Projects are encouraged to adopt this whether they
-are hosted in the Node.js Foundation or not.
+# SpeedUpAmerica Contributing Guide

 The goal of this document is to create a contribution process that:

@@ -12,7 +8,7 @@ The goal of this document is to create a contribution process that:
 * Creates a transparent decision making process which makes it clear how
 contributors can be involved in decision making.

-This document is based on much prior art in the Node.js community, io.js,
+> This document is based on prior art in the Node.js community, io.js,
 and the Node.js project.

 ## Vocabulary
```

``` diff
$ git diff ../CODE_OF_CONDUCT.md CODE_OF_CONDUCT.md
diff --git a/../CODE_OF_CONDUCT.md b/CODE_OF_CONDUCT.md
index b469f56..11bf763 100644
--- a/../CODE_OF_CONDUCT.md
+++ b/CODE_OF_CONDUCT.md
@@ -55,7 +55,7 @@ further defined and clarified by project maintainers.
 ## Enforcement

 Instances of abusive, harassing, or otherwise unacceptable behavior may be
-reported by contacting the project team at report@nodejs.org. All
+reported by contacting a member of the Technical Committiee. All
 complaints will be reviewed and investigated and will result in a response that
 is deemed necessary and appropriate to the circumstances. The project team is
 obligated to maintain confidentiality with regard to the reporter of an incident.
@@ -65,21 +65,11 @@ Project maintainers who do not follow or enforce the Code of Conduct in good
 faith may face temporary or permanent repercussions as determined by other
 members of the project's leadership.

-To learn more about the process of how moderators enforce the Code of Conduct,
-review the [Moderation Policy] and [Requesting Moderation].
-
-[Moderation Policy]: https://github.com/nodejs/admin/blob/master/Moderation-Policy.md#moderation-policy
-[Requesting Moderation]: https://github.com/nodejs/admin/blob/master/Moderation-Policy.md#requesting-moderation
-
 ## Attribution

 This Code of Conduct is adapted from the [Contributor Covenant][homepage],
 version 1.4, available at https://www.contributor-covenant.org/version/1/4/

-## Appendix A: The report@nodejs.org Alias
-
-*Note*: At the current time, all email sent to the `report@nodejs.org` email
-alias is copied to all members of the [Node.js Moderation Team][].
+> Copied with from [Node.js' Code of Conduct](https://github.com/nodejs/admin/blob/a7c7d0a8b51109d8f6416a1572e649cc90cba20d/CODE_OF_CONDUCT.md)

 [homepage]: http://contributor-covenant.org
-[Node.js Moderation Team]: https://github.com/nodejs/admin/blob/master/Moderation-Policy.md#current-members
```

### CODE REVIEW

**Comment by ryanrolds** [comment]
I inverted the diffs initially, fixed.

**Comment by critzo** [comment]
Thanks @ryanrolds Looks great.

**Comment by ryanrolds** [comment]
Is there anyone that should be added to the TC? I don't believe the TC needs to be limited to engineers but can include anyone with useful domain knowledge. Is there anyone we want to include? Maybe, a stakeholder from Lane County? Should we change the name of the TC committee to something more inclusive?

**Comment by mattsayre** [comment]
> Is there anyone that should be added to the TC? I don't believe the TC needs to be limited to engineers but can include anyone with useful domain knowledge. Is there anyone we want to include? Maybe, a stakeholder from Lane County? Should we change the name of the TC committee to something more inclusive?

Yes, I would put forward Austin Ramirez from Lane County Gov for consideration. He is knowledgeable about the domain and represents a sub-set of the target users. He also is the liaison to the OP, Representative Buch.

**Comment by ryanrolds** [comment]
Do you mind reaching out and getting him in the Slack channel and looking at this PR? Once we are on the same communication channels, I can answer any questions he has?

**Comment by ryanrolds** [comment]
Also, the TC is pretty white and male. Just throwing that out there.

**Comment by Kourchenko** [comment]
> 
> 
> Also, the TC is pretty white and male. Just throwing that out there.

I'm Hispanic :) 

I like this project team contract for contributing. It allows us to establish a basis for working on a team! 
Thanks Ryan!

**Comment by ryanrolds** [comment]
I've gotten 👍  from everyone on the TC and our first committer. I'm going to leave this up through the weekend. Assuming we still have concensus I will merge it. At that time I will make a PR to add Austin Ramirez to the TC as he is our H4C challenge and County rep.

@Kourchenko  You're welcome. My comment about the demographics wasn't a major complaint, just something the TC needs to be cognizant of.

**Comment by nohorse** [comment]
If you want to announce this in the #open-eugene or #open-data channel on the EugeneTech and/or use the switchboard to do a public call for leadership. those are the two most common ways to cast a net.  It's also a great way to avoid being accused later of having a tech-bro star-chamber pulling the strings on a civic project with federal $$$ attached.  It will prolly get announced at the moz-global-sprint kick-off may 1st so that's also a good time to open things back up if you like.

**Pull request merged**
