### PR TITLE
Switching map to Mapbox GL JS

### PR DESCRIPTION
**Pull request by Kourchenko**
> Edited by Ryan. Diego started the work and I picked it up when he went on vacation.

* Upgrades map to Mapbox GL JS
* Broke the logic up so map related logic is in it's own file
* Moved JS scripts to just before the map containers in the template files, now Mapbox files aren't loaded on the home page

> Don't merge this after it's approved.

### CODE REVIEW

**Comment by ryanrolds** [comment]
Diego is going on vacation. I'm picking this branch up where he left off.

**Comment by ryanrolds** [comment]
This is a work in progress, I wish GitHub allowed turning PRs into drafts.

**Comment by noahbrenner** [comment]
@ryanrolds What do you think of creating a `WIP` label to serve that purpose? Not perfect, but it would be visible from the PR list.

**Comment by ryanrolds** [comment]
GitHub added draft PRs recently. I think drafts are a great way to flag something as a WIP.

**Comment by ryanrolds** [comment]
This is ready to review.

**Pull request merged**
