### PR TITLE
update to StandardSQL, table name, query constraints

### LINKED ISSUE #15: Revise M-Lab queries to use StandardSQL and current M-Lab BigQuery tables
`submissions_importer.rb` has [outdated queries](https://github.com/Hack4Eugene/SpeedUpAmerica/blob/master/app/classes/submissions_importer.rb#L66-L133)to M-Lab BigQuery tables. Revise and test updated queries. Needed to resolve #2 

Table name should change from `plx.google:m_lab.ndt.all` to `measurement-lab.release.ndt_all`, and I'll work on revised queries to post here or in a PR.

### PR DESCRIPTION
**Pull request by critzo**
This PR updates the queries to M-Lab's BigQuery dataset. Included updates:
* use StandardSQL, remove LegacySQL functions
* current M-Lab dataset & table name
* update query constraints per [M-Lab's documentation](https://www.measurementlab.net/data/docs/bq/ndtmetrics/)

Resolves #15, unblocks #2

### CODE REVIEW

**Comment by ryanrolds** [comment]
Thank you @critzo. Looking at this shortly.

**Comment by ryanrolds** [comment]
After setting a default value when no MLab data exists in the submissions table, I get:
```
$ docker-compose run frontend rake import_mlab_submissions
Started job to import MLab speed test submissions
rake aborted!
BigQuery::ClientError: 3.23 - 3.49: Unrecognized function timestamp_micros
[Try using standard SQL (https://cloud.google.com/bigquery/docs/reference/standard-sql/enabling-standard-sql)]
/usr/local/bundle/gems/bigquery-client-0.4.0/lib/bigquery-client/client.rb:44:in `handle_error'
/usr/local/bundle/gems/bigquery-client-0.4.0/lib/bigquery-client/client.rb:26:in `access_api'
/usr/local/bundle/gems/bigquery-client-0.4.0/lib/bigquery-client/jobs.rb:19:in `jobs_query'
/usr/local/bundle/gems/bigquery-client-0.4.0/lib/bigquery-client/run_query.rb:18:in `execute_query'
/usr/local/bundle/gems/bigquery-client-0.4.0/lib/bigquery-client/run_query.rb:10:in `call'
/usr/local/bundle/gems/bigquery-client-0.4.0/lib/bigquery-client/jobs.rb:14:in `query'
/usr/local/bundle/gems/bigquery-client-0.4.0/lib/bigquery-client/jobs.rb:6:in `sql'
/suyc/app/classes/submissions_importer.rb:52:in `import'
/suyc/lib/tasks/submissions.rake:13:in `block in <top (required)>'
/usr/local/bundle/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => import_mlab_submissions
(See full trace by running task with --trace)
```

**Comment by ryanrolds** [comment]
I just pushed a branch (issue-2_bigquery_imports) that has your changes and a fix for running rake import task.

**Comment by critzo** [comment]
@ryanrolds PR #23 will supercede this PR. Closing.

**Pull request closed without merging**
