### PR TITLE
Update region_controller.rb

### PR DESCRIPTION
**Pull request by mattsayre**
changes links on my branch, so I can push to master. Tried from Dave's and things went sideways.

### CODE REVIEW

**Comment by webaissance** [comment]
@mattsayre - it's not letting me approve this. 
It says:

Review required
At least 1 approving review is required by reviewers with write access. 
1 pending reviewer

Merging is blocked
Merging can be performed automatically with 1 approving review.

Maybe I don't have write access so I can't approve?

**Comment by mattsayre** [comment]
Just changed your privs to 'Admin' from 'Write', which are the same as mine.
Try again? @webaissance

**Review by webaissance — APPROVED** [review]
These changes are approved. - @webaissance

**Comment by webaissance** [comment]
Thanks @mattsayre  - I believe that did the trick!

**Pull request merged**
